import { Joke } from './types';

const rawJokes = [
  "Wissenschaftler haben herausgefunden... – und sind wieder hineingegangen.",
  "Heute war Schrottwichteln im Kindergarten – wir sind die neuen Eltern von Kevin.",
  "Wie nennt man jemanden, der so tut, als würde er etwas werfen? – Scheinwerfer.",
  "Was ist grün, schlau und stellt viele Fragen? – Günther Lauch.",
  "Ich hab einem Hippster ins Bein geschossen – jetzt hoppst´er.",
  "Wie nennt man einen Bumerang, der nicht zurückkommt? – Stock.",
  "Wie heißt die Frau von Herkules? – Frau Kules.",
  'Sagt die eine Kuh "Muuuh", sagt die andere "Hey, das wollte ich auch gerade sagen."',
  "Seit ich clean bin, sprechen meine Freunde nicht mehr mit mir. Der Toaster und die Lampe auch nicht.",
  "Warum fliegen Vögel im Winter in Richtung Süden? – Weil es schneller geht als laufen.",
  '"Anton, findest du, dass ich eine schlechte Mutter bin?" "Ich heiße Paul."',
  'Lehrerin zu Peter: Tut mir leid, aber ich kann Dir in Französisch maximal eine 5- geben“. Peter darauf: "Gracias!"',
  "Wie nennt man einen Hund, der zaubern kann? – Labrakadabrador.",
  '"Man, ich versteh echt nicht, warum meine Pflanzen immer vertrocknen!?" – Jochen, steht auf dem Schlauch.',
  "Ich wollte eigentlich einen Witz über die Deutsche Bahn machen, aber ich glaube der kommt nicht an.",
  "Wie nennt man ein helles Mammut? – Hellmut.",
  "Was sagt ein Bauer, der seinen Trecker sucht? – Wo ist mein Trecker?",
  "Egal wie leer du im Kopf bist, manche Leute sind Lehrer.",
  'Ein Beamter zum anderen: "Was haben denn die Leute? Wir machen doch gar nichts."',
  "Wie nennt man ein Einhorn mit 2 Hörnern? – Stier.",
  "Warum summen Bienen? – Weil sie den Text nicht kennen.",
  "Ich hab gestern meinen Besen verkauft. – I don’t kehr.",
  "Wohin geht ein Reh ohne Haare? – In die Reha-Klinik.",
  "Warum sieht man Ameisen nicht in Kirchen? – Weil sie In-Sekten sind.",
  "Wie heißt der Bruder von Elvis? – Zwölvis.",
  "Wie heißt ein Hund ohne Beine? – Ist egal, der kommt eh nicht, wenn man ihn ruft.",
  "Wenn man Buchstabensuppe auskotzt, ist das dann gebrochenes Deutsch?",
  "Wie heißt ein Spanier ohne Auto? – Carlos.",
  "Was sagt das Schwein zum anderen? – Es ist Wurst, was aus uns wird.",
  "Ich wollte gerade Spiderman anrufen, aber er hatte kein Netz.",
  "Bei welchem Arzt ist Pinocchio in Behandlung? – Beim Holz-Nasen-Ohren-Arzt.",
  "Welche Sprache wird in der Sauna gesprochen? – Schwitzerdeutsch.",
  "Was sind die letzten Worte einer Giftschlange? – Mist, jetzt habe ich mir auf die Zunge gebissen.",
  "Wie nennt man ein Rudel aggressiver Wölfe? – Wolfgang.",
  "Welches Gebäck weiß auf alles eine Antwort? – Der Googlehupf.",
  "Was steht auf dem Grab eines Mathematikers? – Damit hat er nicht gerechnet.",
  "Was kauft ein Frosch im Supermarkt? – Quaaark.",
  "Was ist lila und sitzt in der Kirche in der ersten Reihe? – Eine Frommbeere.",
  "Treffen sich zwei Jäger – beide tot.",
  'Treffen sich zwei Rechtsanwälte, fragt der eine: "Und wie?" Sagt der andere: "Nichts zu klagen."',
  "Wie machen Igel Liebe? – Megavorsichtig.",
  'Treffen sich zwei Hellseher, fragt der eine: "Kommst du mit?" Sagt der andere: "Ne, da war ich gestern schon."',
  'Kommt ein Skelett zum Arzt, sagt der Arzt: "Bisschen spät, was?"',
  'Was beginnt mit "T" und endet mit "itten"? – Tiefkühlfritten.',
  "Was bekommt der Kannibale, der zu spät zum Essen kommt? – Die kalte Schulter.",
  "Was trinkt ein Mann vor dem Sex? – Einen Kaffee Latte.",
  "Was ist klein, grün und dreieckig? – Das kleine grüne Dreieck.",
  'Fragt der Walfisch den Thunfisch: "Was soll ich tun, Fisch?" Sagt der Thunfisch zum Walfisch: "Du hast die Wahl Fisch!"',
  "Was sagt die Null zur Acht? – Schicker Gürtel.",
  "Was macht die Knackwurst so knackig? – Das N.",
  "Was sitzt auf dem Ast und weint? – Eine Heule.",
  "Warum findet der Henker nie den Rückweg? – Weil er nur die Hinrichtung kennt.",
  "Wie heißt der Bruder vom Werwolf? – Warumwolf.",
  '"Oma, hast du meine Tabletten gesehen? Da steht LSD drauf." "Vergiss mal die Tabletten, hast du den Drachen in der Küche gesehen?"',
  "Was ist die Hälfte von sechs? – Halb sechs.",
  '"Wie lange habe ich noch zu leben, Doktor?" "10!" "10? 10 was? Monate? Jahre?" "9, 8, 7"',
  "Ich hab meinem Freund gerade einen Limonadenwitz erzählt. Fanta lustig.",
  "Was ist der Unterschied zwischen Lidl und Schule? – Lidl lohnt sich.",
  "Wer wohnt im Dschungel und schummelt immer? – Mogli.",
  "Was ist weiß und stört beim Essen? – Eine Lawine.",
  "Wenn sich ein Wissenschaftler ein Sandwich macht, ist es dann wissenschaftlich belegt?",
  "Wieso können Skelette schlecht lügen? – Weil sie so gut zu durchschauen sind.",
  "Wie nennt man ein Kaninchen im Fitnessstudio? – Pumpernickel.",
  "Wo sind Elefanten heimisch? – In Rüsselsheim.",
  "Warum klaut Robin Hood Deodorants? – Weil er es unter den Armen verteilt.",
  "Wie lautet der Vorname vom Reh? – Kartoffelpü.",
  "Was sagt der große Stift zum kleinen Stift? – Wachs mal Stift.",
  "Ich habe den Joghurt fallen gelassen. Er war nicht mehr haltbar.",
  '"Und was ist so dein Lieblingsfilm?" "Tesafilm ist ein echt guter Streifen."',
  "Wisst ihr was der Hammer ist? – Ein Werkzeug.",
  "Warum hat die Polizei den Dieb nicht verhaftet? – Er hatte eine Anti-Haft-Beschichtung.",
  "Wie nennt man einen Deutschen im All? – Alman.",
  "Was atmen Lockführer? – Zugluft.",
  "Welcher Vogel vögelt gerne? – Der Fuckuck.",
  "Wie heißt ein Ritter ohne Helm? – Willhelm.",
  "Wie war die Stimmung in der DDR? – Sie hielt sich in Grenzen.",
  "Wie heißt ein Bär, der fliegen kann? – Hubschraubär.",
  'Treffen sich zwei Ziegen, fragt die eine: "Kommst du heute Abend mit in den Club?" Sagt der andere: "Nein, hab keinen Bock."',
  "Welche Schuhe kauft jemand, der zwei linke Füße hat? – Flipflips.",
  "Wie nennt man Sex mit Gegenständen? Dingsbums.",
  'Gast zum Kellner: "Die Suppe war köstlich. Richten Sie dem Koch ein Kompliment aus." Kellner zum Koch: "Günther, du bist wunderschön!"',
  "Wann gehen U-Boote unter? – Am Tag der offenen Tür.",
  "Magst du Chemie-Witze? – Chlor!",
  "Was macht ein arbeitsloser Schauspieler? – Spielt keine Rolle.",
  "Wie nennt man ein Überraschungsessen? – Topf Secret.",
  'Treffen sich zwei Unsichtbare, sagt der eine: "Dich habe ich ja schon lange nicht mehr gesehen!"',
  "Was passiert, wenn man nachts in der Bäckerei anruft? – Die Mehlbox geht dran.",
  "Wie nennt man einen unentschlossenen japanischen Krieger? – Nunja.",
  "Wie heißt die Auszeichnung für besonders, brave, ruhige Hunde? – No-Bell-Preis.",
  "Was sitzt auf einem Baum und winkt? – Ein Huhu.",
  "Was schwimmt auf dem Wasser und fängt mit Z an? – Zwei Enten.",
  "Der Prinz ist angepisst – Rapunzel ließ ihren Harn herunter.",
  'In Australien schaut ein Pinguin total verschwitzt aus dem Beutel eines Kängurus und sagt: "Scheiß Schüleraustausch."',
  'Sagt ein Gast zur Kellnerin: "Hätten Sie noch Milch zum Kaffee?" Sagt die Kellnerin: "Ich hab fettarme." Antwortet der Gast: "Das seh ich. Aber mit denen können Sie mir doch Milch bringen."',
  "Hat mich eine Prostituierte am Bahnhof angesprochen. Sie meinte für 30 Euro macht sie alles, was ich will. Jetzt rate mal, wer heute Abend bei mir das Laminat verlegt.",
  'Geht eine schwangere Frau in eine Bäckerei und sagt: "Ich bekomme ein Brot." Sagt der Bäcker: "Sachen gibt’s."',
  'Was sagt ein Haifisch, wenn er einen Surfer sieht? "Das ist aber nett. Serviert auf Frühstücksbrettchen."',
  "Was ist ein Keks unter einem Baum? Ein schattiges Plätzchen!",
  "Was macht eine Bombe im Bordell? Puff!",
  "Hab mich vorhin ausgesperrt. War ganz aus dem Häuschen.",
  "Mein Hund kennt alle Straßen in- und auswendig. Ich nenne ihn Google Mops.",
  "Ich habe mit der Pflanze ausgemacht, sie nur noch einmal im Monat zu gießen. Sie ist darauf eingegangen.",
  "Was macht ein Clown im Büro? Faxen."
];

export const jokes: Joke[] = rawJokes.map((text, index) => ({
  id: index + 1,
  text
}));

// Sounds
export const SOUNDS = {
    bell: "https://assets.mixkit.co/active_storage/sfx/2005/2005-preview.mp3",
    laugh: "https://assets.mixkit.co/active_storage/sfx/2192/2192-preview.mp3"
};
